/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ProfileImport } from './routes/profile'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as IndexImport } from './routes/index'
import { Route as InstructorSimulationImport } from './routes/instructor/simulation'
import { Route as StudentTutorialIndexImport } from './routes/student/tutorial/index'
import { Route as StudentAssessmentIndexImport } from './routes/student/assessment/index'
import { Route as InstructorTutorialIndexImport } from './routes/instructor/tutorial/index'
import { Route as InstructorAssessmentIndexImport } from './routes/instructor/assessment/index'
import { Route as StudentTutorialHowToRateGroupMembersImport } from './routes/student/tutorial/how-to-rate-group-members'
import { Route as StudentTutorialHowToJoinAnAssessmentImport } from './routes/student/tutorial/how-to-join-an-assessment'
import { Route as StudentTutorialHowToJoinAGroupImport } from './routes/student/tutorial/how-to-join-a-group'
import { Route as StudentAssessmentAssessmentIdImport } from './routes/student/assessment/$assessmentId'
import { Route as InstructorTutorialWebavaliaTerminologyImport } from './routes/instructor/tutorial/webavalia-terminology'
import { Route as InstructorTutorialQassTerminologyImport } from './routes/instructor/tutorial/qass-terminology'
import { Route as InstructorTutorialHowToViewPeerRatingsImport } from './routes/instructor/tutorial/how-to-view-peer-ratings'
import { Route as InstructorTutorialHowToUseAutomaticScoreCalculationImport } from './routes/instructor/tutorial/how-to-use-automatic-score-calculation'
import { Route as InstructorTutorialHowToSetupAssessmentImport } from './routes/instructor/tutorial/how-to-setup-assessment'
import { Route as InstructorTutorialHowToSetTheAssessmentDatesImport } from './routes/instructor/tutorial/how-to-set-the-assessment-dates'
import { Route as InstructorTutorialHowToEditGroupScoresAndStudentScoresImport } from './routes/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
import { Route as InstructorTutorialHowToCreateAGroupAndAddMembersImport } from './routes/instructor/tutorial/how-to-create-a-group-and-add-members'
import { Route as InstructorTutorialHowToAddStudentsImport } from './routes/instructor/tutorial/how-to-add-students'
import { Route as InstructorAssessmentAssessmentIdIndexImport } from './routes/instructor/assessment/$assessmentId/index'
import { Route as InstructorAssessmentAssessmentIdGroupGroupIdIndexImport } from './routes/instructor/assessment/$assessmentId/group/$groupId/index'
import { Route as InstructorAssessmentAssessmentIdGroupGroupIdMemberImport } from './routes/instructor/assessment/$assessmentId/group/$groupId/member'
import { Route as InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdImport } from './routes/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'

// Create/Update Routes

const VerifyEmailRoute = VerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InstructorSimulationRoute = InstructorSimulationImport.update({
  id: '/instructor/simulation',
  path: '/instructor/simulation',
  getParentRoute: () => rootRoute,
} as any)

const StudentTutorialIndexRoute = StudentTutorialIndexImport.update({
  id: '/student/tutorial/',
  path: '/student/tutorial/',
  getParentRoute: () => rootRoute,
} as any)

const StudentAssessmentIndexRoute = StudentAssessmentIndexImport.update({
  id: '/student/assessment/',
  path: '/student/assessment/',
  getParentRoute: () => rootRoute,
} as any)

const InstructorTutorialIndexRoute = InstructorTutorialIndexImport.update({
  id: '/instructor/tutorial/',
  path: '/instructor/tutorial/',
  getParentRoute: () => rootRoute,
} as any)

const InstructorAssessmentIndexRoute = InstructorAssessmentIndexImport.update({
  id: '/instructor/assessment/',
  path: '/instructor/assessment/',
  getParentRoute: () => rootRoute,
} as any)

const StudentTutorialHowToRateGroupMembersRoute =
  StudentTutorialHowToRateGroupMembersImport.update({
    id: '/student/tutorial/how-to-rate-group-members',
    path: '/student/tutorial/how-to-rate-group-members',
    getParentRoute: () => rootRoute,
  } as any)

const StudentTutorialHowToJoinAnAssessmentRoute =
  StudentTutorialHowToJoinAnAssessmentImport.update({
    id: '/student/tutorial/how-to-join-an-assessment',
    path: '/student/tutorial/how-to-join-an-assessment',
    getParentRoute: () => rootRoute,
  } as any)

const StudentTutorialHowToJoinAGroupRoute =
  StudentTutorialHowToJoinAGroupImport.update({
    id: '/student/tutorial/how-to-join-a-group',
    path: '/student/tutorial/how-to-join-a-group',
    getParentRoute: () => rootRoute,
  } as any)

const StudentAssessmentAssessmentIdRoute =
  StudentAssessmentAssessmentIdImport.update({
    id: '/student/assessment/$assessmentId',
    path: '/student/assessment/$assessmentId',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialWebavaliaTerminologyRoute =
  InstructorTutorialWebavaliaTerminologyImport.update({
    id: '/instructor/tutorial/webavalia-terminology',
    path: '/instructor/tutorial/webavalia-terminology',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialQassTerminologyRoute =
  InstructorTutorialQassTerminologyImport.update({
    id: '/instructor/tutorial/qass-terminology',
    path: '/instructor/tutorial/qass-terminology',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToViewPeerRatingsRoute =
  InstructorTutorialHowToViewPeerRatingsImport.update({
    id: '/instructor/tutorial/how-to-view-peer-ratings',
    path: '/instructor/tutorial/how-to-view-peer-ratings',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToUseAutomaticScoreCalculationRoute =
  InstructorTutorialHowToUseAutomaticScoreCalculationImport.update({
    id: '/instructor/tutorial/how-to-use-automatic-score-calculation',
    path: '/instructor/tutorial/how-to-use-automatic-score-calculation',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToSetupAssessmentRoute =
  InstructorTutorialHowToSetupAssessmentImport.update({
    id: '/instructor/tutorial/how-to-setup-assessment',
    path: '/instructor/tutorial/how-to-setup-assessment',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToSetTheAssessmentDatesRoute =
  InstructorTutorialHowToSetTheAssessmentDatesImport.update({
    id: '/instructor/tutorial/how-to-set-the-assessment-dates',
    path: '/instructor/tutorial/how-to-set-the-assessment-dates',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute =
  InstructorTutorialHowToEditGroupScoresAndStudentScoresImport.update({
    id: '/instructor/tutorial/how-to-edit-group-scores-and-student-scores',
    path: '/instructor/tutorial/how-to-edit-group-scores-and-student-scores',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToCreateAGroupAndAddMembersRoute =
  InstructorTutorialHowToCreateAGroupAndAddMembersImport.update({
    id: '/instructor/tutorial/how-to-create-a-group-and-add-members',
    path: '/instructor/tutorial/how-to-create-a-group-and-add-members',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorTutorialHowToAddStudentsRoute =
  InstructorTutorialHowToAddStudentsImport.update({
    id: '/instructor/tutorial/how-to-add-students',
    path: '/instructor/tutorial/how-to-add-students',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorAssessmentAssessmentIdIndexRoute =
  InstructorAssessmentAssessmentIdIndexImport.update({
    id: '/instructor/assessment/$assessmentId/',
    path: '/instructor/assessment/$assessmentId/',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute =
  InstructorAssessmentAssessmentIdGroupGroupIdIndexImport.update({
    id: '/instructor/assessment/$assessmentId/group/$groupId/',
    path: '/instructor/assessment/$assessmentId/group/$groupId/',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute =
  InstructorAssessmentAssessmentIdGroupGroupIdMemberImport.update({
    id: '/instructor/assessment/$assessmentId/group/$groupId/member',
    path: '/instructor/assessment/$assessmentId/group/$groupId/member',
    getParentRoute: () => rootRoute,
  } as any)

const InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute =
  InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdImport.update(
    {
      id: '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId',
      path: '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId',
      getParentRoute: () => rootRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/instructor/simulation': {
      id: '/instructor/simulation'
      path: '/instructor/simulation'
      fullPath: '/instructor/simulation'
      preLoaderRoute: typeof InstructorSimulationImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-add-students': {
      id: '/instructor/tutorial/how-to-add-students'
      path: '/instructor/tutorial/how-to-add-students'
      fullPath: '/instructor/tutorial/how-to-add-students'
      preLoaderRoute: typeof InstructorTutorialHowToAddStudentsImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-create-a-group-and-add-members': {
      id: '/instructor/tutorial/how-to-create-a-group-and-add-members'
      path: '/instructor/tutorial/how-to-create-a-group-and-add-members'
      fullPath: '/instructor/tutorial/how-to-create-a-group-and-add-members'
      preLoaderRoute: typeof InstructorTutorialHowToCreateAGroupAndAddMembersImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-edit-group-scores-and-student-scores': {
      id: '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
      path: '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
      fullPath: '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
      preLoaderRoute: typeof InstructorTutorialHowToEditGroupScoresAndStudentScoresImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-set-the-assessment-dates': {
      id: '/instructor/tutorial/how-to-set-the-assessment-dates'
      path: '/instructor/tutorial/how-to-set-the-assessment-dates'
      fullPath: '/instructor/tutorial/how-to-set-the-assessment-dates'
      preLoaderRoute: typeof InstructorTutorialHowToSetTheAssessmentDatesImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-setup-assessment': {
      id: '/instructor/tutorial/how-to-setup-assessment'
      path: '/instructor/tutorial/how-to-setup-assessment'
      fullPath: '/instructor/tutorial/how-to-setup-assessment'
      preLoaderRoute: typeof InstructorTutorialHowToSetupAssessmentImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-use-automatic-score-calculation': {
      id: '/instructor/tutorial/how-to-use-automatic-score-calculation'
      path: '/instructor/tutorial/how-to-use-automatic-score-calculation'
      fullPath: '/instructor/tutorial/how-to-use-automatic-score-calculation'
      preLoaderRoute: typeof InstructorTutorialHowToUseAutomaticScoreCalculationImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/how-to-view-peer-ratings': {
      id: '/instructor/tutorial/how-to-view-peer-ratings'
      path: '/instructor/tutorial/how-to-view-peer-ratings'
      fullPath: '/instructor/tutorial/how-to-view-peer-ratings'
      preLoaderRoute: typeof InstructorTutorialHowToViewPeerRatingsImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/qass-terminology': {
      id: '/instructor/tutorial/qass-terminology'
      path: '/instructor/tutorial/qass-terminology'
      fullPath: '/instructor/tutorial/qass-terminology'
      preLoaderRoute: typeof InstructorTutorialQassTerminologyImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/webavalia-terminology': {
      id: '/instructor/tutorial/webavalia-terminology'
      path: '/instructor/tutorial/webavalia-terminology'
      fullPath: '/instructor/tutorial/webavalia-terminology'
      preLoaderRoute: typeof InstructorTutorialWebavaliaTerminologyImport
      parentRoute: typeof rootRoute
    }
    '/student/assessment/$assessmentId': {
      id: '/student/assessment/$assessmentId'
      path: '/student/assessment/$assessmentId'
      fullPath: '/student/assessment/$assessmentId'
      preLoaderRoute: typeof StudentAssessmentAssessmentIdImport
      parentRoute: typeof rootRoute
    }
    '/student/tutorial/how-to-join-a-group': {
      id: '/student/tutorial/how-to-join-a-group'
      path: '/student/tutorial/how-to-join-a-group'
      fullPath: '/student/tutorial/how-to-join-a-group'
      preLoaderRoute: typeof StudentTutorialHowToJoinAGroupImport
      parentRoute: typeof rootRoute
    }
    '/student/tutorial/how-to-join-an-assessment': {
      id: '/student/tutorial/how-to-join-an-assessment'
      path: '/student/tutorial/how-to-join-an-assessment'
      fullPath: '/student/tutorial/how-to-join-an-assessment'
      preLoaderRoute: typeof StudentTutorialHowToJoinAnAssessmentImport
      parentRoute: typeof rootRoute
    }
    '/student/tutorial/how-to-rate-group-members': {
      id: '/student/tutorial/how-to-rate-group-members'
      path: '/student/tutorial/how-to-rate-group-members'
      fullPath: '/student/tutorial/how-to-rate-group-members'
      preLoaderRoute: typeof StudentTutorialHowToRateGroupMembersImport
      parentRoute: typeof rootRoute
    }
    '/instructor/assessment/': {
      id: '/instructor/assessment/'
      path: '/instructor/assessment'
      fullPath: '/instructor/assessment'
      preLoaderRoute: typeof InstructorAssessmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/instructor/tutorial/': {
      id: '/instructor/tutorial/'
      path: '/instructor/tutorial'
      fullPath: '/instructor/tutorial'
      preLoaderRoute: typeof InstructorTutorialIndexImport
      parentRoute: typeof rootRoute
    }
    '/student/assessment/': {
      id: '/student/assessment/'
      path: '/student/assessment'
      fullPath: '/student/assessment'
      preLoaderRoute: typeof StudentAssessmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/student/tutorial/': {
      id: '/student/tutorial/'
      path: '/student/tutorial'
      fullPath: '/student/tutorial'
      preLoaderRoute: typeof StudentTutorialIndexImport
      parentRoute: typeof rootRoute
    }
    '/instructor/assessment/$assessmentId/': {
      id: '/instructor/assessment/$assessmentId/'
      path: '/instructor/assessment/$assessmentId'
      fullPath: '/instructor/assessment/$assessmentId'
      preLoaderRoute: typeof InstructorAssessmentAssessmentIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/instructor/assessment/$assessmentId/group/$groupId/member': {
      id: '/instructor/assessment/$assessmentId/group/$groupId/member'
      path: '/instructor/assessment/$assessmentId/group/$groupId/member'
      fullPath: '/instructor/assessment/$assessmentId/group/$groupId/member'
      preLoaderRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdMemberImport
      parentRoute: typeof rootRoute
    }
    '/instructor/assessment/$assessmentId/group/$groupId/': {
      id: '/instructor/assessment/$assessmentId/group/$groupId/'
      path: '/instructor/assessment/$assessmentId/group/$groupId'
      fullPath: '/instructor/assessment/$assessmentId/group/$groupId'
      preLoaderRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId': {
      id: '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
      path: '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
      fullPath: '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
      preLoaderRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instructor/simulation': typeof InstructorSimulationRoute
  '/instructor/tutorial/how-to-add-students': typeof InstructorTutorialHowToAddStudentsRoute
  '/instructor/tutorial/how-to-create-a-group-and-add-members': typeof InstructorTutorialHowToCreateAGroupAndAddMembersRoute
  '/instructor/tutorial/how-to-edit-group-scores-and-student-scores': typeof InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute
  '/instructor/tutorial/how-to-set-the-assessment-dates': typeof InstructorTutorialHowToSetTheAssessmentDatesRoute
  '/instructor/tutorial/how-to-setup-assessment': typeof InstructorTutorialHowToSetupAssessmentRoute
  '/instructor/tutorial/how-to-use-automatic-score-calculation': typeof InstructorTutorialHowToUseAutomaticScoreCalculationRoute
  '/instructor/tutorial/how-to-view-peer-ratings': typeof InstructorTutorialHowToViewPeerRatingsRoute
  '/instructor/tutorial/qass-terminology': typeof InstructorTutorialQassTerminologyRoute
  '/instructor/tutorial/webavalia-terminology': typeof InstructorTutorialWebavaliaTerminologyRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/tutorial/how-to-join-a-group': typeof StudentTutorialHowToJoinAGroupRoute
  '/student/tutorial/how-to-join-an-assessment': typeof StudentTutorialHowToJoinAnAssessmentRoute
  '/student/tutorial/how-to-rate-group-members': typeof StudentTutorialHowToRateGroupMembersRoute
  '/instructor/assessment': typeof InstructorAssessmentIndexRoute
  '/instructor/tutorial': typeof InstructorTutorialIndexRoute
  '/student/assessment': typeof StudentAssessmentIndexRoute
  '/student/tutorial': typeof StudentTutorialIndexRoute
  '/instructor/assessment/$assessmentId': typeof InstructorAssessmentAssessmentIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/member': typeof InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute
  '/instructor/assessment/$assessmentId/group/$groupId': typeof InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId': typeof InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instructor/simulation': typeof InstructorSimulationRoute
  '/instructor/tutorial/how-to-add-students': typeof InstructorTutorialHowToAddStudentsRoute
  '/instructor/tutorial/how-to-create-a-group-and-add-members': typeof InstructorTutorialHowToCreateAGroupAndAddMembersRoute
  '/instructor/tutorial/how-to-edit-group-scores-and-student-scores': typeof InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute
  '/instructor/tutorial/how-to-set-the-assessment-dates': typeof InstructorTutorialHowToSetTheAssessmentDatesRoute
  '/instructor/tutorial/how-to-setup-assessment': typeof InstructorTutorialHowToSetupAssessmentRoute
  '/instructor/tutorial/how-to-use-automatic-score-calculation': typeof InstructorTutorialHowToUseAutomaticScoreCalculationRoute
  '/instructor/tutorial/how-to-view-peer-ratings': typeof InstructorTutorialHowToViewPeerRatingsRoute
  '/instructor/tutorial/qass-terminology': typeof InstructorTutorialQassTerminologyRoute
  '/instructor/tutorial/webavalia-terminology': typeof InstructorTutorialWebavaliaTerminologyRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/tutorial/how-to-join-a-group': typeof StudentTutorialHowToJoinAGroupRoute
  '/student/tutorial/how-to-join-an-assessment': typeof StudentTutorialHowToJoinAnAssessmentRoute
  '/student/tutorial/how-to-rate-group-members': typeof StudentTutorialHowToRateGroupMembersRoute
  '/instructor/assessment': typeof InstructorAssessmentIndexRoute
  '/instructor/tutorial': typeof InstructorTutorialIndexRoute
  '/student/assessment': typeof StudentAssessmentIndexRoute
  '/student/tutorial': typeof StudentTutorialIndexRoute
  '/instructor/assessment/$assessmentId': typeof InstructorAssessmentAssessmentIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/member': typeof InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute
  '/instructor/assessment/$assessmentId/group/$groupId': typeof InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId': typeof InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instructor/simulation': typeof InstructorSimulationRoute
  '/instructor/tutorial/how-to-add-students': typeof InstructorTutorialHowToAddStudentsRoute
  '/instructor/tutorial/how-to-create-a-group-and-add-members': typeof InstructorTutorialHowToCreateAGroupAndAddMembersRoute
  '/instructor/tutorial/how-to-edit-group-scores-and-student-scores': typeof InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute
  '/instructor/tutorial/how-to-set-the-assessment-dates': typeof InstructorTutorialHowToSetTheAssessmentDatesRoute
  '/instructor/tutorial/how-to-setup-assessment': typeof InstructorTutorialHowToSetupAssessmentRoute
  '/instructor/tutorial/how-to-use-automatic-score-calculation': typeof InstructorTutorialHowToUseAutomaticScoreCalculationRoute
  '/instructor/tutorial/how-to-view-peer-ratings': typeof InstructorTutorialHowToViewPeerRatingsRoute
  '/instructor/tutorial/qass-terminology': typeof InstructorTutorialQassTerminologyRoute
  '/instructor/tutorial/webavalia-terminology': typeof InstructorTutorialWebavaliaTerminologyRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/tutorial/how-to-join-a-group': typeof StudentTutorialHowToJoinAGroupRoute
  '/student/tutorial/how-to-join-an-assessment': typeof StudentTutorialHowToJoinAnAssessmentRoute
  '/student/tutorial/how-to-rate-group-members': typeof StudentTutorialHowToRateGroupMembersRoute
  '/instructor/assessment/': typeof InstructorAssessmentIndexRoute
  '/instructor/tutorial/': typeof InstructorTutorialIndexRoute
  '/student/assessment/': typeof StudentAssessmentIndexRoute
  '/student/tutorial/': typeof StudentTutorialIndexRoute
  '/instructor/assessment/$assessmentId/': typeof InstructorAssessmentAssessmentIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/member': typeof InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute
  '/instructor/assessment/$assessmentId/group/$groupId/': typeof InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute
  '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId': typeof InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/instructor/simulation'
    | '/instructor/tutorial/how-to-add-students'
    | '/instructor/tutorial/how-to-create-a-group-and-add-members'
    | '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
    | '/instructor/tutorial/how-to-set-the-assessment-dates'
    | '/instructor/tutorial/how-to-setup-assessment'
    | '/instructor/tutorial/how-to-use-automatic-score-calculation'
    | '/instructor/tutorial/how-to-view-peer-ratings'
    | '/instructor/tutorial/qass-terminology'
    | '/instructor/tutorial/webavalia-terminology'
    | '/student/assessment/$assessmentId'
    | '/student/tutorial/how-to-join-a-group'
    | '/student/tutorial/how-to-join-an-assessment'
    | '/student/tutorial/how-to-rate-group-members'
    | '/instructor/assessment'
    | '/instructor/tutorial'
    | '/student/assessment'
    | '/student/tutorial'
    | '/instructor/assessment/$assessmentId'
    | '/instructor/assessment/$assessmentId/group/$groupId/member'
    | '/instructor/assessment/$assessmentId/group/$groupId'
    | '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/instructor/simulation'
    | '/instructor/tutorial/how-to-add-students'
    | '/instructor/tutorial/how-to-create-a-group-and-add-members'
    | '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
    | '/instructor/tutorial/how-to-set-the-assessment-dates'
    | '/instructor/tutorial/how-to-setup-assessment'
    | '/instructor/tutorial/how-to-use-automatic-score-calculation'
    | '/instructor/tutorial/how-to-view-peer-ratings'
    | '/instructor/tutorial/qass-terminology'
    | '/instructor/tutorial/webavalia-terminology'
    | '/student/assessment/$assessmentId'
    | '/student/tutorial/how-to-join-a-group'
    | '/student/tutorial/how-to-join-an-assessment'
    | '/student/tutorial/how-to-rate-group-members'
    | '/instructor/assessment'
    | '/instructor/tutorial'
    | '/student/assessment'
    | '/student/tutorial'
    | '/instructor/assessment/$assessmentId'
    | '/instructor/assessment/$assessmentId/group/$groupId/member'
    | '/instructor/assessment/$assessmentId/group/$groupId'
    | '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/instructor/simulation'
    | '/instructor/tutorial/how-to-add-students'
    | '/instructor/tutorial/how-to-create-a-group-and-add-members'
    | '/instructor/tutorial/how-to-edit-group-scores-and-student-scores'
    | '/instructor/tutorial/how-to-set-the-assessment-dates'
    | '/instructor/tutorial/how-to-setup-assessment'
    | '/instructor/tutorial/how-to-use-automatic-score-calculation'
    | '/instructor/tutorial/how-to-view-peer-ratings'
    | '/instructor/tutorial/qass-terminology'
    | '/instructor/tutorial/webavalia-terminology'
    | '/student/assessment/$assessmentId'
    | '/student/tutorial/how-to-join-a-group'
    | '/student/tutorial/how-to-join-an-assessment'
    | '/student/tutorial/how-to-rate-group-members'
    | '/instructor/assessment/'
    | '/instructor/tutorial/'
    | '/student/assessment/'
    | '/student/tutorial/'
    | '/instructor/assessment/$assessmentId/'
    | '/instructor/assessment/$assessmentId/group/$groupId/member'
    | '/instructor/assessment/$assessmentId/group/$groupId/'
    | '/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InstructorSimulationRoute: typeof InstructorSimulationRoute
  InstructorTutorialHowToAddStudentsRoute: typeof InstructorTutorialHowToAddStudentsRoute
  InstructorTutorialHowToCreateAGroupAndAddMembersRoute: typeof InstructorTutorialHowToCreateAGroupAndAddMembersRoute
  InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute: typeof InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute
  InstructorTutorialHowToSetTheAssessmentDatesRoute: typeof InstructorTutorialHowToSetTheAssessmentDatesRoute
  InstructorTutorialHowToSetupAssessmentRoute: typeof InstructorTutorialHowToSetupAssessmentRoute
  InstructorTutorialHowToUseAutomaticScoreCalculationRoute: typeof InstructorTutorialHowToUseAutomaticScoreCalculationRoute
  InstructorTutorialHowToViewPeerRatingsRoute: typeof InstructorTutorialHowToViewPeerRatingsRoute
  InstructorTutorialQassTerminologyRoute: typeof InstructorTutorialQassTerminologyRoute
  InstructorTutorialWebavaliaTerminologyRoute: typeof InstructorTutorialWebavaliaTerminologyRoute
  StudentAssessmentAssessmentIdRoute: typeof StudentAssessmentAssessmentIdRoute
  StudentTutorialHowToJoinAGroupRoute: typeof StudentTutorialHowToJoinAGroupRoute
  StudentTutorialHowToJoinAnAssessmentRoute: typeof StudentTutorialHowToJoinAnAssessmentRoute
  StudentTutorialHowToRateGroupMembersRoute: typeof StudentTutorialHowToRateGroupMembersRoute
  InstructorAssessmentIndexRoute: typeof InstructorAssessmentIndexRoute
  InstructorTutorialIndexRoute: typeof InstructorTutorialIndexRoute
  StudentAssessmentIndexRoute: typeof StudentAssessmentIndexRoute
  StudentTutorialIndexRoute: typeof StudentTutorialIndexRoute
  InstructorAssessmentAssessmentIdIndexRoute: typeof InstructorAssessmentAssessmentIdIndexRoute
  InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute
  InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute
  InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute: typeof InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InstructorSimulationRoute: InstructorSimulationRoute,
  InstructorTutorialHowToAddStudentsRoute:
    InstructorTutorialHowToAddStudentsRoute,
  InstructorTutorialHowToCreateAGroupAndAddMembersRoute:
    InstructorTutorialHowToCreateAGroupAndAddMembersRoute,
  InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute:
    InstructorTutorialHowToEditGroupScoresAndStudentScoresRoute,
  InstructorTutorialHowToSetTheAssessmentDatesRoute:
    InstructorTutorialHowToSetTheAssessmentDatesRoute,
  InstructorTutorialHowToSetupAssessmentRoute:
    InstructorTutorialHowToSetupAssessmentRoute,
  InstructorTutorialHowToUseAutomaticScoreCalculationRoute:
    InstructorTutorialHowToUseAutomaticScoreCalculationRoute,
  InstructorTutorialHowToViewPeerRatingsRoute:
    InstructorTutorialHowToViewPeerRatingsRoute,
  InstructorTutorialQassTerminologyRoute:
    InstructorTutorialQassTerminologyRoute,
  InstructorTutorialWebavaliaTerminologyRoute:
    InstructorTutorialWebavaliaTerminologyRoute,
  StudentAssessmentAssessmentIdRoute: StudentAssessmentAssessmentIdRoute,
  StudentTutorialHowToJoinAGroupRoute: StudentTutorialHowToJoinAGroupRoute,
  StudentTutorialHowToJoinAnAssessmentRoute:
    StudentTutorialHowToJoinAnAssessmentRoute,
  StudentTutorialHowToRateGroupMembersRoute:
    StudentTutorialHowToRateGroupMembersRoute,
  InstructorAssessmentIndexRoute: InstructorAssessmentIndexRoute,
  InstructorTutorialIndexRoute: InstructorTutorialIndexRoute,
  StudentAssessmentIndexRoute: StudentAssessmentIndexRoute,
  StudentTutorialIndexRoute: StudentTutorialIndexRoute,
  InstructorAssessmentAssessmentIdIndexRoute:
    InstructorAssessmentAssessmentIdIndexRoute,
  InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute:
    InstructorAssessmentAssessmentIdGroupGroupIdMemberRoute,
  InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute:
    InstructorAssessmentAssessmentIdGroupGroupIdIndexRoute,
  InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute:
    InstructorAssessmentAssessmentIdGroupGroupIdPeerRatingScoringComponentScoringComponentIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forgot-password",
        "/profile",
        "/reset-password",
        "/signin",
        "/signup",
        "/verify-email",
        "/instructor/simulation",
        "/instructor/tutorial/how-to-add-students",
        "/instructor/tutorial/how-to-create-a-group-and-add-members",
        "/instructor/tutorial/how-to-edit-group-scores-and-student-scores",
        "/instructor/tutorial/how-to-set-the-assessment-dates",
        "/instructor/tutorial/how-to-setup-assessment",
        "/instructor/tutorial/how-to-use-automatic-score-calculation",
        "/instructor/tutorial/how-to-view-peer-ratings",
        "/instructor/tutorial/qass-terminology",
        "/instructor/tutorial/webavalia-terminology",
        "/student/assessment/$assessmentId",
        "/student/tutorial/how-to-join-a-group",
        "/student/tutorial/how-to-join-an-assessment",
        "/student/tutorial/how-to-rate-group-members",
        "/instructor/assessment/",
        "/instructor/tutorial/",
        "/student/assessment/",
        "/student/tutorial/",
        "/instructor/assessment/$assessmentId/",
        "/instructor/assessment/$assessmentId/group/$groupId/member",
        "/instructor/assessment/$assessmentId/group/$groupId/",
        "/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.tsx"
    },
    "/instructor/simulation": {
      "filePath": "instructor/simulation.tsx"
    },
    "/instructor/tutorial/how-to-add-students": {
      "filePath": "instructor/tutorial/how-to-add-students.tsx"
    },
    "/instructor/tutorial/how-to-create-a-group-and-add-members": {
      "filePath": "instructor/tutorial/how-to-create-a-group-and-add-members.tsx"
    },
    "/instructor/tutorial/how-to-edit-group-scores-and-student-scores": {
      "filePath": "instructor/tutorial/how-to-edit-group-scores-and-student-scores.tsx"
    },
    "/instructor/tutorial/how-to-set-the-assessment-dates": {
      "filePath": "instructor/tutorial/how-to-set-the-assessment-dates.tsx"
    },
    "/instructor/tutorial/how-to-setup-assessment": {
      "filePath": "instructor/tutorial/how-to-setup-assessment.tsx"
    },
    "/instructor/tutorial/how-to-use-automatic-score-calculation": {
      "filePath": "instructor/tutorial/how-to-use-automatic-score-calculation.tsx"
    },
    "/instructor/tutorial/how-to-view-peer-ratings": {
      "filePath": "instructor/tutorial/how-to-view-peer-ratings.tsx"
    },
    "/instructor/tutorial/qass-terminology": {
      "filePath": "instructor/tutorial/qass-terminology.tsx"
    },
    "/instructor/tutorial/webavalia-terminology": {
      "filePath": "instructor/tutorial/webavalia-terminology.tsx"
    },
    "/student/assessment/$assessmentId": {
      "filePath": "student/assessment/$assessmentId.tsx"
    },
    "/student/tutorial/how-to-join-a-group": {
      "filePath": "student/tutorial/how-to-join-a-group.tsx"
    },
    "/student/tutorial/how-to-join-an-assessment": {
      "filePath": "student/tutorial/how-to-join-an-assessment.tsx"
    },
    "/student/tutorial/how-to-rate-group-members": {
      "filePath": "student/tutorial/how-to-rate-group-members.tsx"
    },
    "/instructor/assessment/": {
      "filePath": "instructor/assessment/index.tsx"
    },
    "/instructor/tutorial/": {
      "filePath": "instructor/tutorial/index.tsx"
    },
    "/student/assessment/": {
      "filePath": "student/assessment/index.tsx"
    },
    "/student/tutorial/": {
      "filePath": "student/tutorial/index.tsx"
    },
    "/instructor/assessment/$assessmentId/": {
      "filePath": "instructor/assessment/$assessmentId/index.tsx"
    },
    "/instructor/assessment/$assessmentId/group/$groupId/member": {
      "filePath": "instructor/assessment/$assessmentId/group/$groupId/member.tsx"
    },
    "/instructor/assessment/$assessmentId/group/$groupId/": {
      "filePath": "instructor/assessment/$assessmentId/group/$groupId/index.tsx"
    },
    "/instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId": {
      "filePath": "instructor/assessment/$assessmentId/group/$groupId/peer-rating/scoring-component/$scoringComponentId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
